version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: off

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  - job_name: PowerShell 7.2 on Windows
    job_group: docker
    appveyor_build_worker_image: Visual Studio 2022

  - job_name: PowerShell 7.1 on macOS
    job_group: dockerosx
    appveyor_build_worker_image: macOS

  - job_name: Windows PowerShell 5.1/.NET 4.6.2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2013

  - job_name: Windows PowerShell 5.1/.NET 4.8
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: PowerShell 6.2 on Windows
    job_group: docker
    appveyor_build_worker_image: Visual Studio 2015

  - job_name: PowerShell 7.2 on Ubuntu
    job_group: docker
    appveyor_build_worker_image: Ubuntu

  - job_name: PowerShell 7.1 on Windows
    job_group: docker
    appveyor_build_worker_image: Visual Studio 2019


artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: |
        $ProgressPreference = 'SilentlyContinue'
        iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
        .\build.ps1

# Build in PowerShell
# - matrix:
#     only:
#     - job_group: pwsh
#   build_script:
#   - pwsh: |
#         $ProgressPreference = 'SilentlyContinue'
#         iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
#         ./build.ps1

# Build with docker
- matrix:
    only:
    - job_group: docker
  build_script:
  - docker run rundeck/rundeck

# Build with docker on OSX
- matrix:
    only:
    - job_group: dockerosx
  build_script:
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
    brew install docker;
    docker run rundeck/rundeck;